# .github/release.yml

# This configures GitHub's release note generator:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# See the options here:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors: []

  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🗑 Deprecations
      labels:
        - deprecation
    - title: 💥 Breaking Changes
      labels:
        - api-breaking change
        - classpath-change
    - title: 📦 Artifacts change
      labels:
        - artifacts-change
    - title: 🧰 Maintenance
      labels:
        - build
        - ci
        - dependencies
    - title: ℹ️ Website
      labels:
        - documentation
        - website
    - title: Other Changes
      labels:
        - "*"
