name: "Label Pull Request"

on:
  pull_request:
  merge_group:

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      # see https://github.com/actions/labeler
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: ".github/labeler-config.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # automatically remove labels if the PR changed and made them invalid
          sync-labels: true
