name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: macos-14
    if: github.event.repository.fork == false
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Set version for non-main branch
        if: ${{ github.ref_name != 'main' && !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "ORG_GRADLE_PROJECT_version=${{ github.ref_name }}-SNAPSHOT" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: Check
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: check
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Publish Snapshots
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
